# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mirror_pb2 as mirror__pb2


class AudioServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendAudio = channel.unary_unary(
        '/AudioService/SendAudio',
        request_serializer=mirror__pb2.AudioChunk.SerializeToString,
        response_deserializer=mirror__pb2.Empty.FromString,
        )
    self.GetAudioStream = channel.unary_stream(
        '/AudioService/GetAudioStream',
        request_serializer=mirror__pb2.Empty.SerializeToString,
        response_deserializer=mirror__pb2.AudioChunk.FromString,
        )


class AudioServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendAudio(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAudioStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendAudio': grpc.unary_unary_rpc_method_handler(
          servicer.SendAudio,
          request_deserializer=mirror__pb2.AudioChunk.FromString,
          response_serializer=mirror__pb2.Empty.SerializeToString,
      ),
      'GetAudioStream': grpc.unary_stream_rpc_method_handler(
          servicer.GetAudioStream,
          request_deserializer=mirror__pb2.Empty.FromString,
          response_serializer=mirror__pb2.AudioChunk.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AudioService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
