# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mirror.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mirror.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmirror.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32@\n\x0c\x41udioService\x12\x30\n\tsendAudio\x12\x0b.AudioChunk\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_AUDIOCHUNK = _descriptor.Descriptor(
  name='AudioChunk',
  full_name='AudioChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='AudioChunk.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['AudioChunk'] = _AUDIOCHUNK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioChunk = _reflection.GeneratedProtocolMessageType('AudioChunk', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOCHUNK,
  __module__ = 'mirror_pb2'
  # @@protoc_insertion_point(class_scope:AudioChunk)
  ))
_sym_db.RegisterMessage(AudioChunk)



_AUDIOSERVICE = _descriptor.ServiceDescriptor(
  name='AudioService',
  full_name='AudioService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=73,
  serialized_end=137,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendAudio',
    full_name='AudioService.sendAudio',
    index=0,
    containing_service=None,
    input_type=_AUDIOCHUNK,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUDIOSERVICE)

DESCRIPTOR.services_by_name['AudioService'] = _AUDIOSERVICE

# @@protoc_insertion_point(module_scope)
